export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_QUIZZES_START = "FETCH_QUIZZES_START";
export const FETCH_QUIZZES_SUCCESS = "FETCH_QUIZZES_SUCCESS";
export const FETCH_QUIZZES_FAIL = "FETCH_QUIZZES_FAIL";

export const SET_AUTH_REDIRECT_PATH = " SET_AUTH_REDIRECT_PATH";

export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_USER_DETAILS_FAIL = "SET_USER_DETAILS_FAIL";
export const CHANGE_AWARD_1 = "CHANGE_AWARD_1";
export const CHANGE_AWARD_2 = "CHANGE_AWARD_2";
export const CHANGE_AWARD_3 = "CHANGE_AWARD_3";
