export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_QUIZZES_START = "FETCH_QUIZZES_START";
export const FETCH_QUIZZES_SUCCESS = "FETCH_QUIZZES_SUCCESS";
export const FETCH_QUIZZES_FAIL = "FETCH_QUIZZES_FAIL";
export const QUIZ_FILTER = "QUIZ_FILTER";
export const QUIZ_SEARCH = "QUIZ_SEARCH";
export const QUIZ_START = "QUIZ_START";
export const SUBMIT_QUIZ_START = "SUBMIT_QUIZ_START";
export const SUBMIT_QUIZ_SUCCESS = "SUBMIT_QUIZ_SUCCESS";
export const SUBMIT_QUIZ_FAIL = "SUBMIT_QUIZ_FAIL";

export const SET_AUTH_REDIRECT_PATH = " SET_AUTH_REDIRECT_PATH";

export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const SIGN_UP_SEND = "SIGN_UP_SEND";
export const SIGN_UP_SEND_SUCCESS = "SIGN_UP_SEND_SUCCESS";
export const SIGN_UP_SEND_FAIL = "SIGN_UP_SEND_FAIL";
export const SET_SIGNUP_REDIRECT_PATH = "SET_SIGNUP_REDIRECT_PATH";
export const RESET_SIGN_UP = "RESET_SIGN_UP";

export const FETCH_USER_DATA_START = "FETCH_USER_DATA_START";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAIL = "FETCH_USER_DATA_FAIL";

export const UPDATE_USER_DATA_SUCCESS = "UPDATE_USER_DATA_SUCCESS";
export const UPDATE_USER_DATA_START = "UPDATE_USER_DATA_START";
export const UPDATE_USER_DATA_FAIL = "UPDATE_USER_DATA_FAIL";
export const FETCH_USER_QUIZZES_START = "FETCH_QUIZZES_START";
export const FETCH_USER_QUIZZES_SUCCESS = "FETCH_QUIZZES_SUCCESS";
export const FETCH_USER_QUIZZES_FAIL = "FETCH_QUIZZES_FAIL";
